### ISSUE TITLE
Implement the Vault.sol to the Deploy.ts file

### ISSUE THREAD

**Issue by kimanikelly** [zapproject/zap-hardhat#138]
## Summary
The Vault.sol file should be added to deploy.ts getting it ready for testnet & mainnet deployment

## Files
```contracts/zap-miner/Vault.sol```
```scripts/deploy.ts```

## Definition of Done
- Vault.sol should take in the ZapToken.sol and ZapMaster.sol addresses for deployment
- Vault.sol should successfully be deployed to localhost
- Vault.sol should log an address verifying a successful deployment

**Comment by Kaleb47** [comment]
I'll do it
