### ISSUE TITLE
Deploy ZAP Contracts

### ISSUE THREAD

**Issue by logohere** [zapproject/zap-hardhat#3]
### Create a hardhat task to deploy ZAP Contracts.
Definition of done: 
- Zap migrations are preloaded at NPM start
- Refactor migrations.sol

**Comment by pynchmeister** [comment]
I could be wrong but I'm pretty sure migrations.sol is specific to the Truffle framework. I've removed it and everything runs appropriately. This is reflected on the develop branch.

All of the core contracts can be deployed by first running a hardhat node using ```npx hardhat node``` and then running ```npx hardhat run --network localhost scripts/deploy.ts``` in a separate window.
